name: Deploy to IIS

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: [self-hosted]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Stop App Pool
        run: Stop-WebAppPool -Name "vonet.org"
        shell: powershell

      - name: Publish to IIS
        run: dotnet publish --configuration Release --no-build --output C:\inetpub\sites\vonet.org

      - name: Start App Pool
        run: Start-WebAppPool -Name "vonet.org"
        shell: powershell
